<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create permissions table
 *
 * GOVERNANCE: Permissions are module-driven and dynamic.
 * - Auto-generated by modules
 * - DO NOT hardcode permissions
 * - Key format: module.entity.action
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('permissions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('module_id')->nullable()->constrained('modules')->onDelete('cascade');
            $table->string('key')->unique(); // format: module.entity.action
            $table->string('name');
            $table->boolean('is_active')->default(true);
            $table->timestamps();

            $table->index('module_id');
            $table->index('is_active');
            $table->index('key');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('permissions');
    }
};
